Mysql: "root:Ys!1234567@tcp(10.155.2.62)/gin_example?charset=utf8mb4&parseTime=true&loc=Local"

Server:
  Mode: "debug"
  ServicePort: "8080"
  ServiceHost: "0.0.0.0"

LogLevel: "debug"

I18n: "zh" # zh en ja
