name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Run Build
      run: go build -tags=jsoniter -gcflags='-l=4' -ldflags='-s -w' -o gin_example_with_generic ./cmd/cmd.go
