name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.5

    - name: Run Build
      run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -tags=sonic,avx,linux,amd64 -gcflags='-l=4' -ldflags='-s -w' -o gin_example_with_generic ./cmd/cmd.go
